//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "AVCameraViewControllerDelegate.h"
#import "FBAnimationPerformanceTrackerDelegate.h"
#import "NavigationDelegate.h"
#import "ReplyDelegate.h"
#import "SCChatAndFeedViewControllerDelegate.h"
#import "SCFeedTableViewCellDelegate.h"
#import "SCInAppNotificationCacheDelegate.h"
#import "SCInAppNotificationDelegate.h"
#import "SCStartChatDelegate.h"
#import "SCTimeProfilable.h"
#import "SendSnapNavigationControllerDelegate.h"
#import "SendTextControllerDelegate.h"
#import "StatusBarDelegate.h"
#import "SwipeViewParentDelegate.h"
#import "UIScrollViewDelegate.h"

@class AVCameraViewController<SwipeView>, FBAnimationPerformanceTracker, NSMutableSet, NSString, SCAppNotification, SCChatViewController, SCChatViewControllerV2, SCDiscoverViewController<SwipeView>, SCFeedToChatAnimationBlockingView, SCFeedViewController<SwipeView>, SCInAppNotificationCacheController, SCMainScrollView, SCMediaView, SCStatusBarController, SCStoriesViewController<SwipeView><SCDeepLinkableView>, SCUserSession, UIViewController<SwipeView>;

@interface MainViewController : UIViewController <NavigationDelegate, SendTextControllerDelegate, SCFeedTableViewCellDelegate, SCInAppNotificationDelegate, SCInAppNotificationCacheDelegate, StatusBarDelegate, SCStartChatDelegate, SCTimeProfilable, FBAnimationPerformanceTrackerDelegate, UIScrollViewDelegate, AVCameraViewControllerDelegate, SCChatAndFeedViewControllerDelegate, SendSnapNavigationControllerDelegate, ReplyDelegate, SwipeViewParentDelegate>
{
    NSString *_token;
    FBAnimationPerformanceTracker *_animationTracker;
    SCUserSession *_userSession;
    SCChatViewController *_farLeftVC1;
    SCChatViewControllerV2 *_farLeftVC2;
    _Bool _appeared;
    SCAppNotification *_pendingNotificationToProcess;
    SCFeedToChatAnimationBlockingView *_feedToChatAnimationBlockingView;
    _Bool _animatingScroll;
    _Bool _replyingToStoryWithChat;
    _Bool _didReplyToStory;
    _Bool _viewDidScroll;
    _Bool _isObserving;
    AVCameraViewController<SwipeView> *_middleVC;
    UIViewController<SwipeView> *_farLeftVC;
    SCStoriesViewController<SwipeView><SCDeepLinkableView> *_rightVC;
    SCDiscoverViewController<SwipeView> *_farRightVC;
    UIViewController<SwipeView> *_visibleVC;
    NSString *_chatUsername;
    SCMediaView *_mediaView;
    SCInAppNotificationCacheController *_notificationCacheController;
    UIViewController<SwipeView> *_partiallyVisibleVC;
    SCMainScrollView *_scrollView;
    SCStatusBarController *_statusBarController;
    NSMutableSet *_lockScrollRequestIds;
    SCFeedViewController<SwipeView> *_leftVC;
}

+ (id)profiledSelectorNames;
@property(retain, nonatomic) SCFeedViewController<SwipeView> *leftVC; // @synthesize leftVC=_leftVC;
@property(retain, nonatomic) NSMutableSet *lockScrollRequestIds; // @synthesize lockScrollRequestIds=_lockScrollRequestIds;
@property(nonatomic) _Bool isObserving; // @synthesize isObserving=_isObserving;
@property(nonatomic) _Bool viewDidScroll; // @synthesize viewDidScroll=_viewDidScroll;
@property(retain, nonatomic) SCStatusBarController *statusBarController; // @synthesize statusBarController=_statusBarController;
@property(retain, nonatomic) SCMainScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) _Bool didReplyToStory; // @synthesize didReplyToStory=_didReplyToStory;
@property(nonatomic) _Bool replyingToStoryWithChat; // @synthesize replyingToStoryWithChat=_replyingToStoryWithChat;
@property(retain, nonatomic) UIViewController<SwipeView> *partiallyVisibleVC; // @synthesize partiallyVisibleVC=_partiallyVisibleVC;
@property(retain, nonatomic) SCInAppNotificationCacheController *notificationCacheController; // @synthesize notificationCacheController=_notificationCacheController;
@property(retain, nonatomic) SCMediaView *mediaView; // @synthesize mediaView=_mediaView;
@property(retain, nonatomic) NSString *chatUsername; // @synthesize chatUsername=_chatUsername;
@property(nonatomic) _Bool animatingScroll; // @synthesize animatingScroll=_animatingScroll;
@property(retain, nonatomic) UIViewController<SwipeView> *visibleVC; // @synthesize visibleVC=_visibleVC;
@property(retain, nonatomic) SCDiscoverViewController<SwipeView> *farRightVC; // @synthesize farRightVC=_farRightVC;
@property(retain, nonatomic) SCStoriesViewController<SwipeView><SCDeepLinkableView> *rightVC; // @synthesize rightVC=_rightVC;
@property(retain, nonatomic) UIViewController<SwipeView> *farLeftVC; // @synthesize farLeftVC=_farLeftVC;
@property(retain, nonatomic) AVCameraViewController<SwipeView> *middleVC; // @synthesize middleVC=_middleVC;
- (void).cxx_destruct;
- (void)hideFeedToChatAnimationBlockingView;
- (void)showFeedToChatAnimationBlockingViewWithPreviousTapLocation:(struct CGPoint)arg1 delegate:(id)arg2;
- (id)feedToChatAnimationBlockingView;
- (void)traitCollectionDidChange:(id)arg1;
- (void)reportStackTrace:(id)arg1 withSlide:(id)arg2 frameDropped:(long long)arg3;
- (void)reportDurationInMS:(long long)arg1 smallDropEvent:(double)arg2 largeDropEvent:(double)arg3;
- (void)viewDidFullyDisappearForVisibleVC;
- (void)viewDidFullyAppearForVisibleVC;
- (_Bool)isVisibleVCOnMainAxis;
- (id)viewControllers;
- (id)currentViewController;
- (id)getPageViewName;
- (_Bool)logOnViewDidAppear;
- (void)setStatusBarStyle:(long long)arg1 viewController:(id)arg2;
- (void)setStatusBarHidden:(_Bool)arg1 withAnimation:(long long)arg2 viewController:(id)arg3;
- (void)setStatusBarHidden:(_Bool)arg1 viewController:(id)arg2;
- (void)resetDataSourceForDisappearingNotification:(id)arg1;
- (void)handleInAppNotificationPressed:(id)arg1;
- (void)tryDeferredInAppNotification;
- (void)handleInAppNotificationFromSCCP:(id)arg1;
- (void)handleInAppNotificationReceived:(id)arg1;
- (void)handleLocalNotificationPressed:(id)arg1 withAction:(id)arg2;
- (void)handleOpenURLToAddFriend:(id)arg1;
- (void)handleOpenURL:(id)arg1;
- (void)handleApplicationWillEnterForeground;
- (void)handleApplicationDidEnterBackground;
- (void)cellDidEndPulling:(id)arg1;
- (void)cell:(id)arg1 didChangePullingOffset:(double)arg2;
- (void)cellDidBeginPulling:(id)arg1;
- (void)sendTextController:(id)arg1 completedWithStatus:(int)arg2;
- (void)sendPhoneInvites:(id)arg1;
- (void)presentTextToFriendsIfNecessaryWithRecipients:(id)arg1;
- (void)cancelScroll;
- (void)didHideFullscreenSubview;
- (_Bool)isVisibleViewControllerAndCapableOfPlayingSnaps;
- (_Bool)isFrameInVisibleBounds:(id)arg1;
- (_Bool)isRightOfViewController:(id)arg1;
- (_Bool)isLeftOfViewController:(id)arg1;
- (_Bool)isFullyVisible:(id)arg1;
- (_Bool)isPartiallyVisible:(id)arg1;
- (void)dismissPreviewIfPresented;
- (void)didPostStoryWithoutSendingSnap;
- (void)didSendToGallery;
- (void)didSendSnap:(id)arg1 withRecipients:(id)arg2;
- (void)didCancelFromPreview:(id)arg1;
- (void)cleanUpPaymentBlockerResolution;
- (void)cleanUpStoryReply;
- (void)showForceVerifyPhoneAlertWithNotification:(id)arg1;
- (void)statusBarTapped;
- (void)didFollowThrough;
- (void)replyToUsername:(id)arg1 parameters:(id)arg2 fromPageSource:(long long)arg3 completion:(CDUnknownBlockType)arg4;
- (void)setUnstartedChat:(id)arg1;
- (void)setChatUsername:(id)arg1 triggeredByNotification:(_Bool)arg2;
- (void)navigateToChatViewAnimated:(_Bool)arg1;
- (void)navigateToChatView;
- (void)resetFeedVCState;
- (void)cleanUpAllActiveVideosWaitUntilLoaded:(_Bool)arg1;
- (void)backButtonPressed;
- (id)activeChatUsername;
- (_Bool)isAnimatingScroll;
- (void)unlockScrollWithRequestId:(id)arg1;
- (void)lockScrollWithRequestId:(id)arg1;
- (void)setScrollEnabled:(_Bool)arg1;
- (void)friendPressed;
- (void)feedPressed;
- (void)scrollToVC:(id)arg1 animated:(_Bool)arg2 deepLinkURL:(id)arg3 additionalInfo:(id)arg4;
- (void)presentFarRightVCAnimated:(_Bool)arg1 deepLinkURL:(id)arg2 additionalInfo:(id)arg3;
- (void)presentRightVCAnimated:(_Bool)arg1 deepLinkURL:(id)arg2 additionalInfo:(id)arg3;
- (void)presentMiddleVCAnimated:(_Bool)arg1 deepLinkURL:(id)arg2 additionalInfo:(id)arg3;
- (void)presentLeftVCAnimated:(_Bool)arg1 deepLinkURL:(id)arg2 additionalInfo:(id)arg3;
- (void)presentFarLeftVCAnimated:(_Bool)arg1 deepLinkURL:(id)arg2 additionalInfo:(id)arg3;
- (void)presentFarRightVCAnimated:(_Bool)arg1;
- (void)presentRightVCAnimated:(_Bool)arg1;
- (void)presentMiddleVCAnimated:(_Bool)arg1;
- (void)presentLeftVCAnimated:(_Bool)arg1;
- (void)presentFarLeftVCAnimated:(_Bool)arg1;
- (_Bool)canPerformNavigation;
- (void)applicationWillEnterForeground:(id)arg1;
- (_Bool)value:(long long)arg1 closeTo:(long long)arg2;
- (void)handleNewScrollViewContentOffset:(struct CGPoint)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndScrolling:(id)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)goFromViewController:(id)arg1 direction:(long long)arg2 animated:(_Bool)arg3;
- (void)addVCToScrollViewIfNecessary:(id)arg1;
- (void)goRight:(id)arg1 animated:(_Bool)arg2;
- (void)goLeft:(id)arg1 animated:(_Bool)arg2;
- (void)addVCToView:(id)arg1 withFrame:(struct CGRect)arg2;
- (struct CGRect)frameForViewWithHorizontalOffset:(long long)arg1;
- (void)addFarLeftVCToView;
- (void)addFarRightVCToView;
- (void)addLeftVCToView;
- (void)addRightVCToView;
- (void)addMiddleVCToView;
- (id)farLeftVCUnderChatProtocol;
- (void)initFarLeftVC;
- (void)initFarRightVC;
- (void)initRightVC;
- (void)initLeftVC;
- (void)initMiddleVC;
- (void)initScrollView;
- (void)initStatusBarController;
- (void)didAppStartupComplete;
- (void)didLogout:(id)arg1;
- (void)handleQuickAction:(id)arg1 fromBackground:(_Bool)arg2;
- (void)handleAppNotificationReceived:(id)arg1 afterEnteringForeground:(_Bool)arg2;
- (void)dealloc;
- (void)unobserveAll;
- (void)observeAll;
- (_Bool)shouldDisplayStatusBar;
- (_Bool)canShowStatusBarOverlay;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithCapturerToken:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

