//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SCBaseMediaFullScreenDelegate.h"
#import "SCBaseMediaThumbnailDelegate.h"
#import "SCBlockerResolutionResultDelegate.h"
#import "SCCaptionManagerDelegate.h"
#import "SCCardLinkingDelegate.h"
#import "SCChatDrawerSender.h"
#import "SCChatSnapControllerDelegate.h"
#import "SCChatTableViewCellActionDelegate.h"
#import "SCChatTableViewDataSourceDelegate.h"
#import "SCChatTextInputCashTagManagerDelegate.h"
#import "SCChatUserProfileDataSource.h"
#import "SCChatUserProfileNavigationDelegate.h"
#import "SCChatUserProfileViewControllerDelegate.h"
#import "SCHeaderDataSource.h"
#import "SCHeaderDelegate.h"
#import "SCManagedCapturerListener.h"
#import "SCPasscodeForConfirmBlockerDelegate.h"
#import "SCPaymentSwipeReceiverDelegate.h"
#import "SCPaymentSwipeSenderDelegate.h"
#import "SCPlaceholderTextViewPasteMediaDelegate.h"
#import "SCPotentiallyEligibleFlowDelegate.h"
#import "SCPullToDismissControllerGestureDelegate.h"
#import "SCSnapPlayContainer.h"
#import "SCSnapPlayDelegate.h"
#import "SCTimeProfilable.h"
#import "SKStoreProductViewControllerDelegate.h"
#import "SwipeView.h"
#import "UIGestureRecognizerDelegate.h"
#import "UITextViewDelegate.h"

@class NSDictionary, NSMutableArray, NSMutableSet, NSString, NSTextStorage, SCActionSheetCoordinator, SCAppNotification, SCBaseMediaFullScreenView, SCBlockerResolutionInstance, SCCaptionManager, SCCashLongPressGestureRecognizer, SCChat, SCChatActionButton, SCChatKeyboardControl, SCChatSnapController, SCChatTableViewDataSource, SCChatTableViewDelegate, SCChatTextInputCashTagManager, SCChatUserProfileViewController, SCCustomVolumeController, SCDiscoverDSnapExpirationValidator, SCHeader, SCHereHelperView, SCManagedCapturerState, SCMultiScrollTableView, SCPaymentMessage, SCPaymentSwipeReceiverViewController, SCPaymentSwipeSenderViewController, SCPlaceholderTextView, SCPotentiallyEligibleCashUserFlow, SCPullToDismissController, SCText, SCToggleCameraHelperView, SCUserSession, Snap, SnapTrophyMetrics, UIButton, UILabel, UILongPressGestureRecognizer, UIPanGestureRecognizer, UITapGestureRecognizer, UIView, User;

@interface SCChatViewController : UIViewController <SCChatSnapControllerDelegate, SCSnapPlayContainer, SCSnapPlayDelegate, SCChatDrawerSender, UITextViewDelegate, UIGestureRecognizerDelegate, SCCaptionManagerDelegate, SCHeaderDataSource, SCHeaderDelegate, SCChatTableViewCellActionDelegate, SKStoreProductViewControllerDelegate, SCChatTextInputCashTagManagerDelegate, SCCardLinkingDelegate, SCPaymentSwipeSenderDelegate, SCPaymentSwipeReceiverDelegate, SCBlockerResolutionResultDelegate, SCPasscodeForConfirmBlockerDelegate, SCPotentiallyEligibleFlowDelegate, SCManagedCapturerListener, SCTimeProfilable, SCChatTableViewDataSourceDelegate, SCPlaceholderTextViewPasteMediaDelegate, SCBaseMediaThumbnailDelegate, SCChatUserProfileViewControllerDelegate, SCChatUserProfileDataSource, SCChatUserProfileNavigationDelegate, SCBaseMediaFullScreenDelegate, SCPullToDismissControllerGestureDelegate, SwipeView>
{
    _Bool _togglingCamera;
    _Bool _regularSession;
    SCManagedCapturerState *_managedCapturerState;
    NSString *_token;
    SCUserSession *_userSession;
    SCActionSheetCoordinator *_actionSheetCoordinator;
    SCChatSnapController *_chatSnapController;
    _Bool _didAttemptTapToSaveDuringSession;
    _Bool _flippingCamera;
    _Bool _keyboardWasVisible;
    _Bool _lastCharacterEnteredWasEmoji;
    _Bool _showingCamera;
    _Bool _tableShouldScrollToBottom;
    _Bool _takePictureWhenFinishedTogglingCamera;
    _Bool _quickSnapWhileHere;
    _Bool _quickViewVisible;
    _Bool _didCancelPreview;
    _Bool _shouldPresentSwipeToSend;
    _Bool _appIsInactive;
    _Bool _isRTL;
    SCChat *_chat;
    id <SCChatAndFeedViewControllerDelegate> _delegate;
    id <NavigationDelegate> _navigationDelegate;
    id <StatusBarDelegate> _statusBarDelegate;
    id <SwipeViewParentDelegate> _parentDelegate;
    id <ReplyDelegate> _replyDelegate;
    SnapTrophyMetrics *_snapTrophyMetrics;
    SCAppNotification *_sourceNotification;
    SCChatTableViewDataSource *_tableDataSource;
    SCChatTableViewDelegate *_tableDelegate;
    SCBaseMediaFullScreenView *_baseMediaFullScreenView;
    UIView *_containerView;
    UIView *_captureVideoPreviewView;
    SCCaptionManager *_captionManager;
    SCChatKeyboardControl *_keyboardControl;
    SCCustomVolumeController *_customVolumeController;
    UIButton *_emojiSendButton;
    SCHeader *_header;
    UIView *_headerSeparator;
    SCHereHelperView *_hereHelperView;
    SCChatActionButton *_hereQuickSnapButton;
    UITapGestureRecognizer *_chatUserProfileTapGestureRecognizer;
    UIView *_inputView;
    NSString *_lastChatIdToBeReleased;
    NSString *_lastChatIdOnEnter;
    NSMutableSet *_clearChatTimers;
    double _lastRecordedOffset;
    double _lastYOffsetBeforeScrolling;
    UILongPressGestureRecognizer *_longPressGestureRecognizer;
    NSMutableArray *_observedMessages;
    UIPanGestureRecognizer *_panGestureRecognizer;
    UIPanGestureRecognizer *_chatUserProfilePanGestureRecognizer;
    SCCashLongPressGestureRecognizer *_swipeToSendGestureRecognizer;
    SCPotentiallyEligibleCashUserFlow *_potentiallyEligibleFlow;
    Snap *_replaySnap;
    UITapGestureRecognizer *_snapButtonTapGestureRecognizer;
    UILongPressGestureRecognizer *_snapLongPressGestureRecognizer;
    UIPanGestureRecognizer *_snapButtonDragGestureRecognizer;
    double _snapViewingChatOffset;
    SCMultiScrollTableView *_tableView;
    UIView *_tableViewContainer;
    UITapGestureRecognizer *_tapToSkipGestureRecognizer;
    UILabel *_sccpActiveLabel;
    User *_user;
    id <SCVideoChatControllerProtocol> _videoChatVC;
    SCToggleCameraHelperView *_toggleCameraHelperView;
    UITapGestureRecognizer *_quickViewTapGestureRecognizer;
    SCText *_selectedText;
    SCPaymentMessage *_selectedPaymentMessage;
    NSTextStorage *_textInputTextStorage;
    SCPlaceholderTextView *_textInputView;
    SCChatTextInputCashTagManager *_textInputCashTagManager;
    NSDictionary *_attributesOfTextInTextInputView;
    NSDictionary *_attributesOfCashTagInTextInputView;
    CDUnknownBlockType _captureCVVSuccessBlock;
    SCBlockerResolutionInstance *_blockerResolver;
    SCPaymentSwipeSenderViewController *_swipeSenderViewController;
    SCPaymentSwipeReceiverViewController *_swipeReceiverViewController;
    SCDiscoverDSnapExpirationValidator *_dSnapExpirationValidator;
    SCChatUserProfileViewController *_chatUserProfileVC;
    UIView *_chatUserProfileBorder;
    SCPullToDismissController *_pullToDismissController;
    struct CGPoint _currentPoint;
    struct CGPoint _lastFocusedPoint;
}

+ (id)profiledSelectorNames;
+ (double)distanceBetweenPointA:(struct CGPoint)arg1 pointB:(struct CGPoint)arg2;
+ (id)placeHolderColor;
+ (id)placeHolderFont;
+ (id)inputTextFont;
+ (id)inputTextColor;
+ (id)headerSeparatorColor;
@property(retain, nonatomic) SCPullToDismissController *pullToDismissController; // @synthesize pullToDismissController=_pullToDismissController;
@property(retain, nonatomic) UIView *chatUserProfileBorder; // @synthesize chatUserProfileBorder=_chatUserProfileBorder;
@property(retain, nonatomic) SCChatUserProfileViewController *chatUserProfileVC; // @synthesize chatUserProfileVC=_chatUserProfileVC;
@property(retain, nonatomic) SCDiscoverDSnapExpirationValidator *dSnapExpirationValidator; // @synthesize dSnapExpirationValidator=_dSnapExpirationValidator;
@property(nonatomic) _Bool isRTL; // @synthesize isRTL=_isRTL;
@property(nonatomic) _Bool appIsInactive; // @synthesize appIsInactive=_appIsInactive;
@property(nonatomic) _Bool shouldPresentSwipeToSend; // @synthesize shouldPresentSwipeToSend=_shouldPresentSwipeToSend;
@property(retain, nonatomic) SCPaymentSwipeReceiverViewController *swipeReceiverViewController; // @synthesize swipeReceiverViewController=_swipeReceiverViewController;
@property(retain, nonatomic) SCPaymentSwipeSenderViewController *swipeSenderViewController; // @synthesize swipeSenderViewController=_swipeSenderViewController;
@property(retain, nonatomic) SCBlockerResolutionInstance *blockerResolver; // @synthesize blockerResolver=_blockerResolver;
@property(copy, nonatomic) CDUnknownBlockType captureCVVSuccessBlock; // @synthesize captureCVVSuccessBlock=_captureCVVSuccessBlock;
@property(retain, nonatomic) NSDictionary *attributesOfCashTagInTextInputView; // @synthesize attributesOfCashTagInTextInputView=_attributesOfCashTagInTextInputView;
@property(retain, nonatomic) NSDictionary *attributesOfTextInTextInputView; // @synthesize attributesOfTextInTextInputView=_attributesOfTextInTextInputView;
@property(retain, nonatomic) SCChatTextInputCashTagManager *textInputCashTagManager; // @synthesize textInputCashTagManager=_textInputCashTagManager;
@property(retain, nonatomic) SCPlaceholderTextView *textInputView; // @synthesize textInputView=_textInputView;
@property(retain, nonatomic) NSTextStorage *textInputTextStorage; // @synthesize textInputTextStorage=_textInputTextStorage;
@property(retain, nonatomic) SCPaymentMessage *selectedPaymentMessage; // @synthesize selectedPaymentMessage=_selectedPaymentMessage;
@property(retain, nonatomic) SCText *selectedText; // @synthesize selectedText=_selectedText;
@property(nonatomic) _Bool didCancelPreview; // @synthesize didCancelPreview=_didCancelPreview;
@property(nonatomic) _Bool quickViewVisible; // @synthesize quickViewVisible=_quickViewVisible;
@property(retain, nonatomic) UITapGestureRecognizer *quickViewTapGestureRecognizer; // @synthesize quickViewTapGestureRecognizer=_quickViewTapGestureRecognizer;
@property(retain, nonatomic) SCToggleCameraHelperView *toggleCameraHelperView; // @synthesize toggleCameraHelperView=_toggleCameraHelperView;
@property(retain, nonatomic) id <SCVideoChatControllerProtocol> videoChatVC; // @synthesize videoChatVC=_videoChatVC;
@property(nonatomic) _Bool quickSnapWhileHere; // @synthesize quickSnapWhileHere=_quickSnapWhileHere;
@property(retain, nonatomic) User *user; // @synthesize user=_user;
@property(retain, nonatomic) UILabel *sccpActiveLabel; // @synthesize sccpActiveLabel=_sccpActiveLabel;
@property(retain, nonatomic) UITapGestureRecognizer *tapToSkipGestureRecognizer; // @synthesize tapToSkipGestureRecognizer=_tapToSkipGestureRecognizer;
@property(nonatomic) _Bool takePictureWhenFinishedTogglingCamera; // @synthesize takePictureWhenFinishedTogglingCamera=_takePictureWhenFinishedTogglingCamera;
@property(retain, nonatomic) UIView *tableViewContainer; // @synthesize tableViewContainer=_tableViewContainer;
@property(retain, nonatomic) SCMultiScrollTableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) _Bool tableShouldScrollToBottom; // @synthesize tableShouldScrollToBottom=_tableShouldScrollToBottom;
@property(nonatomic) double snapViewingChatOffset; // @synthesize snapViewingChatOffset=_snapViewingChatOffset;
@property(retain, nonatomic) UIPanGestureRecognizer *snapButtonDragGestureRecognizer; // @synthesize snapButtonDragGestureRecognizer=_snapButtonDragGestureRecognizer;
@property(retain, nonatomic) UILongPressGestureRecognizer *snapLongPressGestureRecognizer; // @synthesize snapLongPressGestureRecognizer=_snapLongPressGestureRecognizer;
@property(retain, nonatomic) UITapGestureRecognizer *snapButtonTapGestureRecognizer; // @synthesize snapButtonTapGestureRecognizer=_snapButtonTapGestureRecognizer;
@property(nonatomic) _Bool showingCamera; // @synthesize showingCamera=_showingCamera;
@property(retain, nonatomic) Snap *replaySnap; // @synthesize replaySnap=_replaySnap;
@property(retain, nonatomic) SCPotentiallyEligibleCashUserFlow *potentiallyEligibleFlow; // @synthesize potentiallyEligibleFlow=_potentiallyEligibleFlow;
@property(retain, nonatomic) SCCashLongPressGestureRecognizer *swipeToSendGestureRecognizer; // @synthesize swipeToSendGestureRecognizer=_swipeToSendGestureRecognizer;
@property(retain, nonatomic) UIPanGestureRecognizer *chatUserProfilePanGestureRecognizer; // @synthesize chatUserProfilePanGestureRecognizer=_chatUserProfilePanGestureRecognizer;
@property(retain, nonatomic) UIPanGestureRecognizer *panGestureRecognizer; // @synthesize panGestureRecognizer=_panGestureRecognizer;
@property(retain, nonatomic) NSMutableArray *observedMessages; // @synthesize observedMessages=_observedMessages;
@property(retain, nonatomic) UILongPressGestureRecognizer *longPressGestureRecognizer; // @synthesize longPressGestureRecognizer=_longPressGestureRecognizer;
@property(nonatomic) double lastYOffsetBeforeScrolling; // @synthesize lastYOffsetBeforeScrolling=_lastYOffsetBeforeScrolling;
@property(nonatomic) double lastRecordedOffset; // @synthesize lastRecordedOffset=_lastRecordedOffset;
@property(nonatomic) struct CGPoint lastFocusedPoint; // @synthesize lastFocusedPoint=_lastFocusedPoint;
@property(retain, nonatomic) NSMutableSet *clearChatTimers; // @synthesize clearChatTimers=_clearChatTimers;
@property(copy, nonatomic) NSString *lastChatIdOnEnter; // @synthesize lastChatIdOnEnter=_lastChatIdOnEnter;
@property(copy, nonatomic) NSString *lastChatIdToBeReleased; // @synthesize lastChatIdToBeReleased=_lastChatIdToBeReleased;
@property(nonatomic) _Bool lastCharacterEnteredWasEmoji; // @synthesize lastCharacterEnteredWasEmoji=_lastCharacterEnteredWasEmoji;
@property(nonatomic) _Bool keyboardWasVisible; // @synthesize keyboardWasVisible=_keyboardWasVisible;
@property(retain, nonatomic) UIView *inputView; // @synthesize inputView=_inputView;
@property(retain, nonatomic) UITapGestureRecognizer *chatUserProfileTapGestureRecognizer; // @synthesize chatUserProfileTapGestureRecognizer=_chatUserProfileTapGestureRecognizer;
@property(retain, nonatomic) SCChatActionButton *hereQuickSnapButton; // @synthesize hereQuickSnapButton=_hereQuickSnapButton;
@property(retain, nonatomic) SCHereHelperView *hereHelperView; // @synthesize hereHelperView=_hereHelperView;
@property(retain, nonatomic) UIView *headerSeparator; // @synthesize headerSeparator=_headerSeparator;
@property(retain, nonatomic) SCHeader *header; // @synthesize header=_header;
@property(nonatomic) _Bool flippingCamera; // @synthesize flippingCamera=_flippingCamera;
@property(retain, nonatomic) UIButton *emojiSendButton; // @synthesize emojiSendButton=_emojiSendButton;
@property(nonatomic) _Bool didAttemptTapToSaveDuringSession; // @synthesize didAttemptTapToSaveDuringSession=_didAttemptTapToSaveDuringSession;
@property(retain, nonatomic) SCCustomVolumeController *customVolumeController; // @synthesize customVolumeController=_customVolumeController;
@property(nonatomic) struct CGPoint currentPoint; // @synthesize currentPoint=_currentPoint;
@property(retain, nonatomic) SCChatKeyboardControl *keyboardControl; // @synthesize keyboardControl=_keyboardControl;
@property(retain, nonatomic) SCCaptionManager *captionManager; // @synthesize captionManager=_captionManager;
@property(retain, nonatomic) UIView *captureVideoPreviewView; // @synthesize captureVideoPreviewView=_captureVideoPreviewView;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) SCBaseMediaFullScreenView *baseMediaFullScreenView; // @synthesize baseMediaFullScreenView=_baseMediaFullScreenView;
@property(retain, nonatomic) SCChatTableViewDelegate *tableDelegate; // @synthesize tableDelegate=_tableDelegate;
@property(retain, nonatomic) SCChatTableViewDataSource *tableDataSource; // @synthesize tableDataSource=_tableDataSource;
@property(retain, nonatomic) SCAppNotification *sourceNotification; // @synthesize sourceNotification=_sourceNotification;
@property(retain, nonatomic) SnapTrophyMetrics *snapTrophyMetrics; // @synthesize snapTrophyMetrics=_snapTrophyMetrics;
@property(nonatomic) __weak id <ReplyDelegate> replyDelegate; // @synthesize replyDelegate=_replyDelegate;
@property(nonatomic) __weak id <SwipeViewParentDelegate> parentDelegate; // @synthesize parentDelegate=_parentDelegate;
@property(nonatomic) __weak id <StatusBarDelegate> statusBarDelegate; // @synthesize statusBarDelegate=_statusBarDelegate;
@property(nonatomic) __weak id <NavigationDelegate> navigationDelegate; // @synthesize navigationDelegate=_navigationDelegate;
@property(nonatomic) __weak id <SCChatAndFeedViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) SCChat *chat; // @synthesize chat=_chat;
- (void).cxx_destruct;
- (void)sendVideoNoteWithData:(id)arg1 duration:(double)arg2;
- (void)sendAudioNoteWithData:(id)arg1 duration:(double)arg2;
- (void)sendMediaDrawerMedia:(id)arg1 fromPosition:(unsigned long long)arg2;
- (void)sendSticker:(id)arg1 fromPack:(id)arg2 fromPosition:(unsigned long long)arg3;
- (void)updatePullToDismissFinalCircleFrame;
- (_Bool)shouldTriggerPullToDismissWithSwipeDirection:(unsigned long long)arg1;
- (struct CGRect)iconViewRectForIndexPath:(id)arg1;
- (struct CGRect)iconViewRectForMessage:(id)arg1;
- (void)willTriggerTapToViewAtPoint:(struct CGPoint)arg1;
- (id)chatRecipientUsername;
- (void)goRightWithAnimation:(_Bool)arg1;
- (void)chatUserProfileDisplayNameDidChange;
- (void)chatUserProfileDidDisappear;
- (void)chatUserProfileWillDisappear;
- (void)chatUserProfileDidAppear;
- (void)chatUserProfileWillAppear;
- (void)setChatUserProfileHidden:(_Bool)arg1;
- (void)openOrCloseDrawer:(id)arg1 visible:(_Bool)arg2 animated:(_Bool)arg3 withCompletionBlock:(CDUnknownBlockType)arg4;
- (void)moveDrawer:(id)arg1 atOffset:(double)arg2;
- (void)setUpLayoutConstraintForDrawer:(id)arg1 visible:(_Bool)arg2;
- (struct CGRect)chatUserProfileFrame;
- (_Bool)chatUserProfileVisible;
- (id)messageForCell:(id)arg1;
- (id)messageForCellAtIndexPath:(id)arg1;
- (id)savableItemChatTableCellForIndexPath:(id)arg1;
- (void)handleChatUpdatedWithLastMessageUpdated:(_Bool)arg1;
- (void)onPaymentTapped:(id)arg1;
- (void)onSnapTappedInV1:(id)arg1;
- (void)attemptRetryBlockForMessage:(id)arg1;
- (void)onChatTapped:(id)arg1;
- (void)deleteFailedMessage:(id)arg1;
- (void)saveOrUnsaveMessage:(id)arg1;
- (void)messageDeletedAtIndexPath:(id)arg1;
- (void)messageUserSaveUpdatedAtIndexPath:(id)arg1;
- (void)messageUpdatedAtIndexPath:(id)arg1;
- (void)newMessageAdded:(id)arg1 atIndexPath:(id)arg2;
- (void)refreshChatWithLastMessageUpdated:(_Bool)arg1 withOldMessagesLoaded:(_Bool)arg2;
- (void)updateCell:(id)arg1 withViewModel:(id)arg2;
- (void)productViewControllerDidFinish:(id)arg1;
- (void)confirmResolutionCancelled;
- (void)confirmResolutionFailed;
- (void)confirmResolutionSucceeded;
- (_Bool)canStartEditingCaption;
- (void)cleanUpPaymentBlockerResolution;
- (void)blockerResolutionCancelled;
- (void)blockerResolutionFailedWithError:(id)arg1;
- (void)blockerResolutionSuccessful;
- (_Bool)showEmojiSendForText:(id)arg1 newRange:(struct _NSRange)arg2 newText:(id)arg3;
- (void)showHiddenKeyboardAnimated:(_Bool)arg1;
- (void)hideKeyboardAnimated:(_Bool)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardDidShow:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)followThroughOnSendText;
- (void)captureCVVForPayment:(id)arg1;
- (_Bool)shouldCaptureCVVOnPaymentMessageSend;
- (id)setUpPaymentMessageWithText:(id)arg1 amount:(unsigned long long)arg2 swipe:(_Bool)arg3;
- (void)beginSendingPaymentMessageWithText:(id)arg1 amount:(unsigned long long)arg2 swipe:(_Bool)arg3;
- (void)flowSuccessfullyCompleted;
- (void)cardLinkingCancelled;
- (void)cardLinkingSuccessful;
- (void)presentCardLinkingVCForCashTag;
- (_Bool)shouldShowCashTagButton;
- (void)updateTextOfTextInputViewWithHighlightedCashTagRanges:(id)arg1;
- (void)textInputCashTagManagerDidChangeSwipeToSendMarkerEntered:(id)arg1;
- (void)textInputCashTagManagerDidChangeHighlightedCashTagRanges:(id)arg1;
- (void)textInputCashTagManagerDidChangeInsertionPointContext:(id)arg1;
- (_Bool)changeSelectionOfTextInputView:(struct _NSRange)arg1 forTextInputCashTagManager:(id)arg2;
- (_Bool)changeTextOfTextInputViewInRange:(struct _NSRange)arg1 replacementText:(id)arg2 forTextInputCashTagManager:(id)arg3;
- (id)markedTextRangeOfTextInputViewForTextInputCashTagManager:(id)arg1;
- (struct _NSRange)selectedRangeOfTextInputViewForTextInputCashTagManager:(id)arg1;
- (id)textOfTextInputViewForTextInputCashTagManager:(id)arg1;
- (void)textViewDidEndEditing:(id)arg1;
- (_Bool)textViewShouldEndEditing:(id)arg1;
- (void)textViewDidChangeSelection:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidChange:(id)arg1;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (void)handleTapOnBar:(id)arg1 withMessage:(id)arg2;
- (id)dSnapValidator;
- (void)fullScreenViewWasDismissed:(id)arg1;
- (void)fullScreenViewWillDismiss:(id)arg1;
- (void)fullScreenViewWillAppear:(id)arg1;
- (void)dismissFullScreenView;
- (void)createFullScreenViewFromThumbnailView:(id)arg1;
- (void)didShowPendingDisplayForMedia:(id)arg1;
- (void)didShowCompleteDisplayForMedia:(id)arg1;
- (void)handleLongPressOnThumbnail:(id)arg1 withMessage:(id)arg2;
- (void)handleTapOnThumbnail:(id)arg1 withMessage:(id)arg2;
- (void)animateScrollToBottom;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (id)prepareForActionSheetWithMessage:(id)arg1;
- (void)stackedTableViewCellDidSelectMessage:(id)arg1;
- (void)textTableViewCellDidSelectCashLabelWithCell:(id)arg1;
- (void)textTableViewCell:(id)arg1 didSelectLinkWithPhoneNumber:(id)arg2;
- (void)textTableViewCell:(id)arg1 didSelectLinkWithAddress:(id)arg2;
- (void)textTableViewCell:(id)arg1 didSelectLinkWithURL:(id)arg2 linkAttribute:(id)arg3 urlMediaCardView:(id)arg4 shouldOpen:(_Bool)arg5;
- (void)cancelDelayedChatReleases;
- (void)sendDeleteSignalForReleasedChats;
- (void)releaseChatOnTimer:(id)arg1;
- (void)releaseChatsWithCause:(long long)arg1;
- (void)_setTextForInput:(id)arg1;
- (id)_textFromInput;
- (_Bool)isUserTableOffsetAtBottom;
- (void)chatSnapControllerDidSendSnapOrChatMessage:(id)arg1;
- (void)chatSnapControllerDidComeFromCameraWithoutSendingSnap:(id)arg1;
- (double)lastVerticalForCaptionWithKeyboardHeight:(double)arg1 screenHeight:(double)arg2;
- (void)managedCapturer:(id)arg1 didResetFromRuntimeError:(id)arg2;
- (void)managedCapturer:(id)arg1 didChangeState:(id)arg2;
- (void)asyncCaptureStillImage;
- (void)delayFocusAtPoint:(struct CGPoint)arg1;
- (void)updateTableViewContentSize:(id)arg1;
- (void)addCustomVolumeIgnoringNextVolumeChange:(_Bool)arg1 parentView:(id)arg2;
- (void)addCustomVolumeIgnoringNextVolumeChange:(_Bool)arg1;
- (void)removeCustomVolume;
- (void)setupCustomVolume;
- (void)updateChatActionButtonState;
- (void)hideCashChatHelpIfNecessary;
- (void)showCashChatHelpIfNecessary;
- (void)promptConfirmationForPaymentWithAmount:(unsigned long long)arg1 forSwipe:(_Bool)arg2;
- (void)showQuickViewForGesture:(id)arg1;
- (_Bool)isQuickViewCameraVisible;
- (void)handleSnapBtnGestureForQuickSnap:(id)arg1;
- (void)handleSnapBtnGestureForSnapCash:(id)arg1;
- (void)snapButtonLongPressOrPan:(id)arg1;
- (void)resetSnapButtonRecognizer;
- (void)presentPaymentRainIfNecessary:(id)arg1;
- (void)presentPaymentRainIfNecessary;
- (void)presentSwipesWithCount:(unsigned long long)arg1 wasPresent:(_Bool)arg2;
- (void)didFinishReceivingPaymentSwipes:(id)arg1;
- (void)didFinishSwipeToSend:(id)arg1 completed:(_Bool)arg2;
- (void)didFinishSwipeDown;
- (void)didSwipe:(id)arg1;
- (void)didReceivePaymentSwipe:(id)arg1;
- (_Bool)isSwipingToSend;
- (id)amountString;
- (void)presentSwipeToSendViewController;
- (void)doubleLongPress:(id)arg1;
- (void)restoreFromChatDraftUserInfo:(id)arg1;
- (id)newChatDraftUserInfo;
- (void)sendInputText;
- (void)emojiSendButtonPressed;
- (void)flipCameraForGesture:(id)arg1;
- (void)flipCameraIfNecessaryForGesture:(id)arg1;
- (long long)cameraCount;
- (void)handleSendCashActionInitiatedWithSwipe:(_Bool)arg1;
- (void)handleDidTapCashButton;
- (void)snapButtonTap:(id)arg1;
- (void)configureCaptionOverlayOnView:(id)arg1;
- (_Bool)shouldPopulateSnapCaption;
- (void)pasteGif:(id)arg1;
- (void)pasteImage:(id)arg1;
- (_Bool)isTheUserConsumingMedia;
- (_Bool)isTheUserConsumingSnap;
- (void)_saveChatToGalleryWithRecipient:(id)arg1;
- (void)userDidTakeScreenshot;
- (long long)sourceViewType;
- (_Bool)isVisibleAndCanPlaySnap;
- (id)mediaView;
- (id)mediaContainerView;
- (void)didFinishSnapPlaying:(id)arg1;
- (void)didFailSetUpSnapPlaying:(id)arg1;
- (void)didSucceedSetUpSnapPlaying:(id)arg1;
- (void)longPressBeganForCellWithSnap:(id)arg1;
- (id)messageForPoint:(struct CGPoint)arg1;
- (void)displayTapToSaveDropdownForSavedMessage:(_Bool)arg1;
- (void)handleLongPressForCellWithPaymentMessage:(id)arg1;
- (void)handleLongPressForCellWithBaseMessage:(id)arg1;
- (void)tapToSkip:(id)arg1;
- (void)quickViewTap:(id)arg1;
- (void)longPress:(id)arg1;
- (void)handleOffsetChangedForCells:(double)arg1;
- (void)tapToDismissChatUserProfile:(id)arg1;
- (void)swipeToDismissChatUserProfile:(id)arg1;
- (void)swipe:(id)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRequireFailureOfGestureRecognizer:(id)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)addObserversForMessage:(id)arg1;
- (void)addMessagesObservers;
- (void)removeMessagesObservers;
- (void)resetSnapsObservers;
- (void)removeChatObservers;
- (void)addChatObservers;
- (void)sccpConnectionStatusChanged:(id)arg1;
- (void)updateSCCPLabel;
- (void)sccpDisconnected;
- (void)sccpConnected;
- (_Bool)shouldShowNotificationInCurrentMediaState;
- (void)deviceLocked:(id)arg1;
- (void)endChatSessionIfStarted;
- (void)releaseLeaveChatView;
- (void)didReceiveMemoryWarning;
- (void)viewWillEnterBackground:(id)arg1;
- (void)viewDidBecomeActive:(id)arg1;
- (void)viewWillResignActive:(id)arg1;
- (_Bool)isShowingFullScreenImageOrVideo;
- (_Bool)shouldPopToRootViewController;
- (id)getPageName;
- (id)getPageViewName;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (void)removeInputViewFrameObserver;
- (void)addInputViewFrameObserver;
- (void)leaveChatView;
- (void)enterChatView;
- (void)didSwitchChat;
- (void)willSwitchChat;
- (void)viewDidAppearAtOffset:(double)arg1;
- (void)viewDidPartiallyAppear;
- (void)viewDidFullyDisappear;
- (void)viewDidFullyAppear;
- (void)viewInFullView;
- (double)offsetForFirstViewableChat;
- (double)maximumContentOffset;
- (double)minimumContentOffset;
- (void)resetContentOffset;
- (void)setContentInsetForHeight:(double)arg1;
- (void)resetContentInset;
- (void)_updateButton:(id)arg1 textSize:(struct CGSize)arg2 shouldShowButton:(_Bool)arg3;
- (void)adjustTextInputViewAnimated:(_Bool)arg1;
- (void)resetView;
- (void)dealloc;
- (_Bool)logOnViewDidAppear;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)chatLoadingStateChanged:(id)arg1;
- (void)viewDidLoad;
- (void)rightButtonPressed;
- (void)leftButtonPressed;
- (id)imageForRightButtonInState:(unsigned long long)arg1;
- (id)imageForLeftButtonInState:(unsigned long long)arg1;
- (id)textColorForHeader:(id)arg1;
- (id)titleForHeader:(id)arg1;
- (id)backgroundColorForHeader;
- (id)getSnapPlayControllerInCurrentVC;
- (id)getSnapPlayControllerAndReplaceContainer;
- (void)updateTableHeight:(double)arg1;
- (_Bool)isVideoChatInitialized;
- (void)initVideoChatController;
- (id)chatSnapController;
- (void)initializeLeftShadow;
- (void)initializeSCCPStatusLabel;
- (void)initializeGestures;
- (void)initializeHeaderSeparator;
- (void)initializeInputView;
- (void)initializeChatTable;
- (void)initHeader;
- (void)loadView;
- (id)initWithUser:(id)arg1 userSession:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

