//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCChatViewController.h"

#import "SCVideoChatViewControllerDelegate.h"

@class NSString;

@interface SCChatViewController (VideoChat) <SCVideoChatViewControllerDelegate>
- (_Bool)isH264Enabled;
- (_Bool)isAddlivePresenceEnabled;
- (_Bool)isVideoChatLocked;
- (void)showHereChatHelpNotSupported;
- (void)showHereChatHelp;
- (void)showHereChatHelpIfNecessary;
- (void)onStreamingActivityChanged:(_Bool)arg1;
- (_Bool)pausingDownloadManagerEnabledFromStudy;
- (double)deferredDisconnectTimeFromStudy;
- (id)getCameraHelperView;
- (void)hasReceivedVideoChatBefore;
- (void)resetPresenceTimers;
- (_Bool)shouldPlayRemoteVideoStream;
- (void)remoteVideoFeedEnd;
- (void)remoteVideoFeedStarted;
- (void)remoteStreamStoppedForMedia:(unsigned long long)arg1;
- (void)remoteStreamStartedForMedia:(unsigned long long)arg1;
- (void)remotePeerDisconnected;
- (void)remotePeerConnected;
- (void)localPreviewContainerReady:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (_Bool)isRecipientPresent;
- (void)promptCallInitialized;
- (id)remoteUsername;
- (void)triggerMediaAccessoryPress:(_Bool)arg1;
- (_Bool)fullscreenAccessoryImagesUsed;
- (void)setFullscreenAccessoryImagesUsed:(_Bool)arg1;
- (_Bool)inputViewTransparent;
- (void)setInputViewTransparent:(_Bool)arg1;
- (_Bool)snapAccessoryHidden;
- (void)setSnapAccessoryHidden:(_Bool)arg1;
- (_Bool)keyboardHidden;
- (void)setKeyboardHidden:(_Bool)arg1;
- (_Bool)inputAccessoriesHidden;
- (void)setInputAccessoriesHidden:(_Bool)arg1;
- (void)resetMediaAccessories;
- (void)panInputAccessoriesWithGestureRecognizer:(id)arg1 dragToHide:(_Bool)arg2;
- (void)videoViewDidLongPressOrPanWithGestureRecognizer:(id)arg1;
- (void)updateTableContentInsetForPresenceWithHeight:(double)arg1;
- (void)userBeingActive:(_Bool)arg1;
- (void)releaseChatViewMaybe;
- (void)viewWillEnterBackground;
- (void)viewDidBecomeActive;
- (void)resetVideoChatViewFrame;
- (void)delayEnableIncomingStream;
- (struct CGRect)frameForLiveVideo;
- (_Bool)usesChatGatewayAuth;
- (void)passGestureRecognizerStateChangedToVideoChatVC;
- (void)stopSendingVideoStream;
- (void)startSendingVideoStream;
- (_Bool)receivingVideoStream;
- (_Bool)sendingVideoStream;
- (_Bool)sendingMedia;
- (_Bool)videoChatVisible;
- (void)removeLiveVideoChatView;
- (void)presentVideoChatViewController;
- (void)releaseVideoChat;
- (void)initVideoChatCommons;
- (void)initVideoChatWithHereAuth;
- (void)initVideoChatWithChatAuth;
- (void)tryToInitializeChatGatewayAuth;
- (_Bool)canStartVideoChatSession;
- (_Bool)shouldStartVideoChatSessionUsingPresence;
- (_Bool)shouldStartVideoChatSessionUsingChatGateway;
- (_Bool)shouldStartVideoChatSession;
- (void)resetPresenceIndicator;
- (void)handleSnapBtnGestureForVideoChat:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

