//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "EGORefreshTableHeaderDelegate.h"
#import "SCAnimatedFeedBackgroundViewAnimationDelegate.h"
#import "SCFeedTableViewCellDelegate.h"
#import "SCFeedToChatAnimationBlockingViewDelegate.h"
#import "SCHeaderDataSource.h"
#import "SCHeaderDelegate.h"
#import "SCMiniProfileControllerDelegate.h"
#import "SCPullToDismissControllerGestureDelegate.h"
#import "SCSearchBarDelegate.h"
#import "SCSnapPlayContainer.h"
#import "SCSnapPlayDelegate.h"
#import "SCTableViewCellUpdateDelegate.h"
#import "SCTimeProfilable.h"
#import "SKStoreProductViewControllerDelegate.h"
#import "SwipeView.h"
#import "UIGestureRecognizerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class EGORefreshTableHeaderView, NSArray, NSString, SCAnimatedFeedBackgroundView, SCChat, SCFeedScoreboardView, SCFriendLongPressGestureRecognizer, SCHeader, SCMiniProfileController, SCPullToDismissController, SCSearchBar, SCUpgradeVersionView, SCUserSession, UILabel, UITableView, UITapGestureRecognizer, UIView;

@interface SCFeedViewController : UIViewController <EGORefreshTableHeaderDelegate, SCHeaderDataSource, SCHeaderDelegate, SCTimeProfilable, UITableViewDataSource, UITableViewDelegate, SCSearchBarDelegate, UIGestureRecognizerDelegate, SCAnimatedFeedBackgroundViewAnimationDelegate, SCFeedTableViewCellDelegate, SKStoreProductViewControllerDelegate, SCPullToDismissControllerGestureDelegate, SCSnapPlayDelegate, SCSnapPlayContainer, SCMiniProfileControllerDelegate, SwipeView, SCTableViewCellUpdateDelegate, SCFeedToChatAnimationBlockingViewDelegate>
{
    NSArray *_filteredFeedItemList;
    SCMiniProfileController *_miniProfileController;
    SCUserSession *_userSession;
    _Bool _shouldTapToChatIfNoUnreadContent;
    SCChat *_transitingChat;
    _Bool _searching;
    _Bool _showingSearchBar;
    _Bool _animationInProgress;
    _Bool _reloading;
    _Bool _firstFetchUpdatesRequest;
    _Bool _didLogFirstChatReadyToView;
    _Bool _delayedReloadTableView;
    _Bool _cellSwiping;
    _Bool _viewHasAppeared;
    _Bool _viewHasFullyAppeared;
    id <SCChatAndFeedViewControllerDelegate> _delegate;
    id <SCFeedTableViewCellDelegate> _feedCellDelegate;
    id <SwipeViewParentDelegate> _parentDelegate;
    id <ReplyDelegate> _replyDelegate;
    id <SCStartChatDelegate> _startChatDelegate;
    id <SendSnapNavigationControllerDelegate> _sendSnapNavigationControllerDelegate;
    SCHeader *_header;
    SCFeedScoreboardView *_scoreBoard;
    UITableView *_tableView;
    UILabel *_emptyFeedListPlaceholder;
    id <SCFeedViewDataSourceDelegate> _dataSource;
    SCSearchBar *_searchBar;
    SCAnimatedFeedBackgroundView *_animatedBackgroundView;
    UITapGestureRecognizer *_tapGestureRecognizer;
    SCFriendLongPressGestureRecognizer *_longPressGestureRecognizer;
    UITapGestureRecognizer *_doubleTapGestureRecognizer;
    UITapGestureRecognizer *_tapToSkipGestureRecognizer;
    EGORefreshTableHeaderView *_refreshHeaderView;
    SCUpgradeVersionView *_upgradeHeader;
    double _lastScrolledYOffset;
    double _lastYOffsetBeforeScrolling;
    UILabel *_sccpActiveLabel;
    id <SCFeedItemDelegate> _swipingFeedItem;
    SCPullToDismissController *_pullToDismissController;
    NSString *_viewingCellIdentifier;
    NSString *_selectedUsername;
    UIView *_addContactsFooter;
}

+ (id)profiledSelectorNames;
@property(retain, nonatomic) UIView *addContactsFooter; // @synthesize addContactsFooter=_addContactsFooter;
@property(copy, nonatomic) NSString *selectedUsername; // @synthesize selectedUsername=_selectedUsername;
@property(retain, nonatomic) NSString *viewingCellIdentifier; // @synthesize viewingCellIdentifier=_viewingCellIdentifier;
@property(nonatomic) _Bool viewHasFullyAppeared; // @synthesize viewHasFullyAppeared=_viewHasFullyAppeared;
@property(nonatomic) _Bool viewHasAppeared; // @synthesize viewHasAppeared=_viewHasAppeared;
@property(retain, nonatomic) SCPullToDismissController *pullToDismissController; // @synthesize pullToDismissController=_pullToDismissController;
@property(nonatomic) id <SCFeedItemDelegate> swipingFeedItem; // @synthesize swipingFeedItem=_swipingFeedItem;
@property(nonatomic) _Bool cellSwiping; // @synthesize cellSwiping=_cellSwiping;
@property(nonatomic) _Bool delayedReloadTableView; // @synthesize delayedReloadTableView=_delayedReloadTableView;
@property(retain, nonatomic) UILabel *sccpActiveLabel; // @synthesize sccpActiveLabel=_sccpActiveLabel;
@property(nonatomic) double lastYOffsetBeforeScrolling; // @synthesize lastYOffsetBeforeScrolling=_lastYOffsetBeforeScrolling;
@property(nonatomic) double lastScrolledYOffset; // @synthesize lastScrolledYOffset=_lastScrolledYOffset;
@property(nonatomic) _Bool didLogFirstChatReadyToView; // @synthesize didLogFirstChatReadyToView=_didLogFirstChatReadyToView;
@property(nonatomic) _Bool firstFetchUpdatesRequest; // @synthesize firstFetchUpdatesRequest=_firstFetchUpdatesRequest;
@property(retain, nonatomic) SCUpgradeVersionView *upgradeHeader; // @synthesize upgradeHeader=_upgradeHeader;
@property(retain, nonatomic) EGORefreshTableHeaderView *refreshHeaderView; // @synthesize refreshHeaderView=_refreshHeaderView;
@property(nonatomic) _Bool reloading; // @synthesize reloading=_reloading;
@property(retain, nonatomic) UITapGestureRecognizer *tapToSkipGestureRecognizer; // @synthesize tapToSkipGestureRecognizer=_tapToSkipGestureRecognizer;
@property(retain, nonatomic) UITapGestureRecognizer *doubleTapGestureRecognizer; // @synthesize doubleTapGestureRecognizer=_doubleTapGestureRecognizer;
@property(retain, nonatomic) SCFriendLongPressGestureRecognizer *longPressGestureRecognizer; // @synthesize longPressGestureRecognizer=_longPressGestureRecognizer;
@property(retain, nonatomic) UITapGestureRecognizer *tapGestureRecognizer; // @synthesize tapGestureRecognizer=_tapGestureRecognizer;
@property(nonatomic) _Bool animationInProgress; // @synthesize animationInProgress=_animationInProgress;
@property(retain, nonatomic) SCAnimatedFeedBackgroundView *animatedBackgroundView; // @synthesize animatedBackgroundView=_animatedBackgroundView;
@property(nonatomic) _Bool showingSearchBar; // @synthesize showingSearchBar=_showingSearchBar;
@property(nonatomic) _Bool searching; // @synthesize searching=_searching;
@property(retain, nonatomic) SCSearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(retain, nonatomic) id <SCFeedViewDataSourceDelegate> dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) UILabel *emptyFeedListPlaceholder; // @synthesize emptyFeedListPlaceholder=_emptyFeedListPlaceholder;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) SCFeedScoreboardView *scoreBoard; // @synthesize scoreBoard=_scoreBoard;
@property(retain, nonatomic) SCHeader *header; // @synthesize header=_header;
@property(nonatomic) __weak id <SendSnapNavigationControllerDelegate> sendSnapNavigationControllerDelegate; // @synthesize sendSnapNavigationControllerDelegate=_sendSnapNavigationControllerDelegate;
@property(nonatomic) __weak id <SCStartChatDelegate> startChatDelegate; // @synthesize startChatDelegate=_startChatDelegate;
@property(nonatomic) __weak id <ReplyDelegate> replyDelegate; // @synthesize replyDelegate=_replyDelegate;
@property(nonatomic) __weak id <SwipeViewParentDelegate> parentDelegate; // @synthesize parentDelegate=_parentDelegate;
@property(nonatomic) __weak id <SCFeedTableViewCellDelegate> feedCellDelegate; // @synthesize feedCellDelegate=_feedCellDelegate;
@property(nonatomic) __weak id <SCChatAndFeedViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)didTapOnFeedToChatAnimationBlockingView;
- (void)moveToIndex:(long long)arg1 fromIndex:(long long)arg2;
- (id)getAddSourceTypeForFriend:(id)arg1 controller:(id)arg2;
- (id)userSession;
- (void)didPressSnapButtonForFriend:(id)arg1 controller:(id)arg2;
- (void)didPressChatButtonForFriend:(id)arg1 controller:(id)arg2;
- (void)_presentMiniProfile:(id)arg1;
- (void)didChangePullToDismissWithPercentage:(double)arg1;
- (void)resetViewingCellAnimated:(_Bool)arg1;
- (id)viewingCell;
- (id)createFeedLoadingCell;
- (_Bool)shouldShowNotificationInCurrentMediaState;
- (void)didFinishSnapPlaying:(id)arg1;
- (void)didFailSetUpSnapPlaying:(id)arg1;
- (void)didSucceedSetUpSnapPlaying:(id)arg1;
- (long long)sourceViewType;
- (_Bool)isVisibleAndCanPlaySnap;
- (id)mediaView;
- (id)mediaContainerView;
- (id)feedItemForIndex:(id)arg1;
- (id)feedItemForCell:(id)arg1;
- (void)cellDidEndPulling:(id)arg1;
- (void)cell:(id)arg1 didChangePullingOffset:(double)arg2;
- (void)cellDidBeginPulling:(id)arg1;
- (void)cellDidEndScrolling:(id)arg1;
- (void)cellDidBeginScrolling:(id)arg1;
- (_Bool)isNearLoadingCellIndexPath:(id)arg1;
- (_Bool)isLoadingCellIndexPath:(id)arg1;
- (long long)loadingCellIndexRow;
- (_Bool)isLoadingCellAtPoint:(struct CGPoint)arg1;
- (void)updateFeedCell:(id)arg1;
- (void)updateUpgradeHeaderIfNecessary;
- (void)didLoadTableViewData;
- (void)didFinishReloadData;
- (void)reloadTableViewDataSource;
- (_Bool)egoRefreshTableHeaderDataSourceIsLoading:(id)arg1;
- (void)egoRefreshTableHeaderDidTriggerRefresh:(id)arg1;
- (void)feedBackgroundAnimationDidStop;
- (void)feedBackgroundAnimationDidStart;
- (void)filterResults:(id)arg1;
- (void)searchBarKeyboardWillHide:(id)arg1;
- (void)searchBarDidBeginSearch:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBar:(id)arg1 didSearch:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)imageForRightButtonInState:(unsigned long long)arg1;
- (id)imageForLeftButtonInState:(unsigned long long)arg1;
- (id)textColorForHeader:(id)arg1;
- (id)titleForHeader:(id)arg1;
- (id)backgroundColorForHeader;
- (void)showCameraForUsername:(id)arg1 doubleTap:(_Bool)arg2 context:(id)arg3;
- (void)showCameraForChat:(id)arg1;
- (_Bool)touchesBeganForIndex:(id)arg1;
- (void)updatePullToDismissFinalCircleFrame;
- (_Bool)shouldTriggerPullToDismissWithSwipeDirection:(unsigned long long)arg1;
- (struct CGRect)iconViewRectForIndexPath:(id)arg1;
- (struct CGRect)iconViewRectForFeedItemUsername:(id)arg1;
- (void)willTriggerTapToViewAtPoint:(struct CGPoint)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)handleTapForLoadingCellAtPoint:(struct CGPoint)arg1;
- (void)tapToSkip:(id)arg1;
- (void)doubleTap:(id)arg1;
- (void)longPress:(id)arg1;
- (void)_transitToChatVC:(id)arg1;
- (_Bool)_tapOnSnap:(id)arg1 cell:(id)arg2 position:(struct CGPoint)arg3;
- (void)tap:(id)arg1;
- (_Bool)canMoveTableViewCell;
- (_Bool)shouldDelayUpdateTableView;
- (void)reloadTableView;
- (void)reloadTableViewIfNecessary;
- (void)resetData;
- (void)sccpConnectionStatusChanged:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)userDidTakeScreenshot;
- (void)dataSourceDidChange;
- (void)didReceiveMemoryWarning;
- (void)viewDidFullyDisappear;
- (void)viewDidFullyAppear;
- (void)viewDidPartiallyAppear;
- (void)viewCanAppear;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)viewWillResignActive:(id)arg1;
- (void)didBecomeActive;
- (void)dealloc;
- (void)viewDidLoad;
- (void)updateEmptyFeedListPlaceHolderLabelVisibility;
- (void)updateEmptyFeedListPlaceHolderLabelFrame;
- (void)updateSCCPLabel;
- (void)scrollToTop;
- (_Bool)scrollViewShouldScrollToTop:(id)arg1;
- (void)scrollViewDidEndScrolling:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (double)preferredLeftButtonWidth;
- (void)rightButtonPressed;
- (void)leftButtonPressed;
- (void)pushStartChatView;
- (id)getSnapPlayControllerInCurrentVC;
- (id)getSnapPlayControllerAndReplaceContainer;
- (void)initGestures;
- (void)initializeSCCPStatusLabel;
- (void)navigateToContacts;
- (_Bool)shouldShowAddContactsFooter;
- (void)updateAddContactsFooter;
- (void)initTableView;
- (void)initSearchBar;
- (void)initHeader;
- (void)loadView;
- (id)initWithDataSource:(id)arg1 userSession:(id)arg2;
- (id)getPageName;
- (id)getPageViewName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

