//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCFakePayToReplayDelegate.h"
#import "SCIAPTOSVCDelegate.h"
#import "TTTAttributedLabelDelegate.h"

@class NSDictionary, NSString, SCAlertViewActionButtonController, SCFakePayToReplayFlow, SKProduct, Snap, UIViewController<SCSnapPlayContainer>;

@interface SCSnapPlayController : NSObject <SCFakePayToReplayDelegate, TTTAttributedLabelDelegate, SCIAPTOSVCDelegate>
{
    UIViewController<SCSnapPlayContainer> *_containerViewController;
    long long _containerViewType;
    Snap *_replaySnap;
    NSString *_lastReplayedSnapStackId;
    NSDictionary *_payToReplayProducts;
    Snap *_pendingPayToReplaySnap;
    SKProduct *_selectedProduct;
    SCAlertViewActionButtonController *_cancelBuyCreditsAction;
    SCFakePayToReplayFlow *_fakePayToReplayFlow;
    unsigned long long _selectedFakeNumberOfReplays;
    NSString *_selectedFakeProductId;
    id <SCSnapPlayDelegate> _delegate;
    Snap *_visibleSnap;
}

+ (id)shared;
@property(retain, nonatomic) Snap *replaySnap; // @synthesize replaySnap=_replaySnap;
@property(retain, nonatomic) Snap *visibleSnap; // @synthesize visibleSnap=_visibleSnap;
@property(nonatomic) __weak id <SCSnapPlayDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)getPageViewName;
- (void)didDismissIAPTOSVC;
- (void)attributedLabel:(id)arg1 didSelectLinkWithTextCheckingResult:(id)arg2;
- (void)uploadReceipt:(id)arg1;
- (void)snapFailedToPlay:(id)arg1 withError:(id)arg2;
- (id)getPriceForFakeProductWithProductKey:(id)arg1;
- (void)updatePendingSnapWithFakeTransactionInfo;
- (void)didPaySuccessfully;
- (void)didCancelPay;
- (void)addCreditWithProduct:(id)arg1;
- (void)didFinishedBuyReplayCreditTransaction;
- (void)inAppPurchaseTransactionDidChange:(id)arg1;
- (id)replayButtonTitleWithProductKey:(id)arg1;
- (void)showReplayCreditUpdatePrompt;
- (void)showBuyReplayCreditPrompt;
- (void)retrievePayToReplayProduct;
- (void)failedToPlayToReplaySnapOrSnapStackWithFirstSnap:(id)arg1;
- (void)changeSnapOrSnapStackStateWithFirstSnap:(id)arg1 state:(long long)arg2;
- (void)replaySnapOrSnapStackWithFirstSnap:(id)arg1 isPaidToReplay:(_Bool)arg2;
- (void)updatePendingPayToReplaySnapsToReplay:(id)arg1;
- (id)replayableSnapsForUsername:(id)arg1;
- (void)resetWaitingUpdateCreditsSnaps;
- (void)showFreeReplayAlertView:(id)arg1;
- (void)promptReplaySnap:(id)arg1;
- (_Bool)canReplaySnap;
- (_Bool)shouldFakeIAP;
- (void)didTakeScreenshot:(id)arg1;
- (void)_saveSnapToGalleryWithUserSession:(id)arg1;
- (void)exitMediaViewWithVisibleSnap;
- (void)snapExpired:(id)arg1;
- (void)clearLoadedReplayedSnapAfterHidingSnap:(id)arg1;
- (void)hideSnap:(id)arg1;
- (void)showSnap:(id)arg1;
- (id)sourceTypeString;
- (void)skipVisibleSnap;
- (_Bool)showingMediaView;
- (_Bool)isPlayingSnap;
- (id)visibleSnapUsername;
- (id)mediaView;
- (void)visibleSnapTimeleftChanged:(id)arg1;
- (void)snapStateChanged:(id)arg1 toSnap:(id)arg2;
- (void)observeVisibleSnap:(id)arg1;
- (void)unobserveVisibleSnap:(id)arg1;
- (void)resetFields;
- (void)dealloc;
- (void)switchToContainerVC:(id)arg1 delegate:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

