//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SCLevelViewController.h"
#import "SCMediaContextViewControllerDelegate.h"
#import "SCPullToDismissControllerGestureDelegate.h"
#import "SCReplyToStoryViewControllerDelegate.h"
#import "SCReportSnapControllerDelegate.h"
#import "SCStoriesFullScreenLoadingViewDelegate.h"
#import "SCStoryViewingTutorialDelegate.h"
#import "SCViewingStoryViewControllerDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class FBKVOController, FriendStories, NSArray, NSDictionary, NSMutableArray, NSObject<OS_dispatch_queue>, NSString, SCDeepLinkURL, SCLeveledThumbnailViewController, SCMediaContextViewController, SCMediaView, SCPullToDismissController, SCReplyToStoryViewController, SCReportSnapController, SCStoriesFullScreenLoadingView, SCStoryDiagnosticsLogger, SCStoryExploreLogger, SCStoryLoader, SCStoryLogger, SCStoryUsageLogger, SCStoryViewingSession, SCStoryViewingTutorialController, SCTooltipBalloon, SCUserSession, Story, UIImage, UILongPressGestureRecognizer, UISwipeGestureRecognizer, UITapGestureRecognizer, UIView;

@interface SCViewingStoryViewController : UIViewController <SCPullToDismissControllerGestureDelegate, SCStoryViewingTutorialDelegate, SCMediaContextViewControllerDelegate, SCReplyToStoryViewControllerDelegate, SCStoriesFullScreenLoadingViewDelegate, UIAlertViewDelegate, UIGestureRecognizerDelegate, SCReportSnapControllerDelegate, SCLevelViewController, SCViewingStoryViewControllerDelegate>
{
    SCUserSession *_userSession;
    Story *_storySnap;
    _Bool _unviewed;
    long long _viewingType;
    SCStoryLoader *_storyLoader;
    Story *_visibleStory;
    SCDeepLinkURL *_deepLinkURL;
    NSString *_sharedIdToDisplay;
    _Bool _initialView;
    _Bool _showInitialLoadingView;
    SCStoryViewingSession *_storyViewingSession;
    _Bool _playingStory;
    _Bool _playingStoryHidden;
    SCStoryUsageLogger *_storyUsageLogger;
    SCStoryDiagnosticsLogger *_storyDiagnosticsLogger;
    SCStoryLogger *_storyLogger;
    UITapGestureRecognizer *_tapGestureRecognizer;
    SCMediaContextViewController *_mediaContextViewController;
    SCReplyToStoryViewController *_replyToStoryViewController;
    FBKVOController *_kvoController;
    NSDictionary *_loggingParameters;
    double _currentStoriesTotalTime;
    SCViewingStoryViewController *_seeMoreViewingStoryVC;
    SCStoriesFullScreenLoadingView *_loadingView;
    UIView *_firstFrameView;
    _Bool _hasNextLevelController;
    _Bool _displayingSnap;
    _Bool _errorFetchingNextLevel;
    _Bool _observingLoadedState;
    _Bool _observingUnviewedLoadedState;
    Story *_observingStorySnap;
    _Bool _unloadedWhilePlaying;
    _Bool _showContextMenu;
    _Bool _didFullyDisappear;
    id <SCViewFactory> _backgroundViewFactory;
    SCPullToDismissController *_pullToDismissController;
    SCLeveledThumbnailViewController *_leveledThumbnailVC;
    NSString *_thumbnailId;
    NSObject<OS_dispatch_queue> *_thumbnailQueue;
    UIImage *_thumbnailImage;
    unsigned long long _levelNumber;
    unsigned long long _loadingImageToken;
    NSArray *_parentSeenSnaps;
    NSMutableArray *_levelSeenSnaps;
    id <SCPerforming> _mainPerformer;
    SCStoryViewingTutorialController *_storyViewingTutorialController;
    SCTooltipBalloon *_explorerTooltip;
    SCReportSnapController *_reportSnapController;
    SCStoryExploreLogger *_storyExploreLogger;
    UISwipeGestureRecognizer *_leftSwipeGestureRecognizer;
    _Bool _didShowStorySnapAfterMediaViewWasShown;
    _Bool _loggingSessionInitialized;
    id <SCLevelViewControllerDelegate> _levelViewControllerDelegate;
    id <SwipeViewDelegate> _swipeViewDelegate;
    id <SCViewingStoryViewControllerDelegate> _delegate;
    id <SCLeveledViewNavigatorDelegate> _navigatorDelegate;
    id <SCStoriesStoryViewingState> _storyViewingProgressDelegate;
    unsigned long long _autoAdvanceIndex;
    long long _storySessionId;
    unsigned long long _storyViewingActionContext;
    UILongPressGestureRecognizer *_longPressGestureRecognizer;
    SCMediaView *_mediaView;
    FriendStories *_friendStories;
}

@property(retain, nonatomic) FriendStories *friendStories; // @synthesize friendStories=_friendStories;
@property(retain, nonatomic) SCMediaView *mediaView; // @synthesize mediaView=_mediaView;
@property(retain, nonatomic) UILongPressGestureRecognizer *longPressGestureRecognizer; // @synthesize longPressGestureRecognizer=_longPressGestureRecognizer;
@property(nonatomic) unsigned long long storyViewingActionContext; // @synthesize storyViewingActionContext=_storyViewingActionContext;
@property(nonatomic) long long storySessionId; // @synthesize storySessionId=_storySessionId;
@property(nonatomic) unsigned long long autoAdvanceIndex; // @synthesize autoAdvanceIndex=_autoAdvanceIndex;
@property(nonatomic) __weak id <SCStoriesStoryViewingState> storyViewingProgressDelegate; // @synthesize storyViewingProgressDelegate=_storyViewingProgressDelegate;
@property(nonatomic) __weak id <SCLeveledViewNavigatorDelegate> navigatorDelegate; // @synthesize navigatorDelegate=_navigatorDelegate;
@property(nonatomic) __weak id <SCViewingStoryViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <SwipeViewDelegate> swipeViewDelegate; // @synthesize swipeViewDelegate=_swipeViewDelegate;
@property(nonatomic) __weak id <SCLevelViewControllerDelegate> levelViewControllerDelegate; // @synthesize levelViewControllerDelegate=_levelViewControllerDelegate;
- (void).cxx_destruct;
- (void)setLoadingViewHidden:(_Bool)arg1;
- (_Bool)_isAutoAdvanceTriggered;
- (void)saveIsExplorableMetrics;
- (void)setThumbnailImageForStory:(id)arg1;
- (void)thumbnailStateDidChange:(id)arg1 object:(id)arg2;
- (void)fetchThumbnailForStory:(id)arg1;
- (_Bool)shouldShowCounter;
- (CDUnknownBlockType)thumbnailTappedBehavior;
- (id)_thumbnailId;
- (_Bool)shouldHideStoriesWhenPlayingStops:(long long)arg1;
- (void)viewingStoryController:(id)arg1 didResolveDeepLinkWithSharedId:(id)arg2 username:(id)arg3;
- (void)viewingStoryController:(id)arg1 didSelectDeleteStorySnap:(id)arg2;
- (void)viewingStoryController:(id)arg1 didSelectSaveStorySnap:(id)arg2;
- (void)viewingStoryControllerDidBecomeUnloaded:(id)arg1;
- (void)viewingStoryControllerDidPullToDismissStory:(id)arg1 finishReason:(long long)arg2;
- (void)viewingStoryControllerDidHideStory:(id)arg1;
- (void)viewingStoryControllerDidStopPlayingStory:(id)arg1 exitReason:(long long)arg2;
- (void)viewingStoryController:(id)arg1 failedToShowNextStorySnap:(id)arg2;
- (_Bool)viewingStoryController:(id)arg1 readyToShowNextStorySnap:(id)arg2;
- (void)viewingStoryController:(id)arg1 didFinishStory:(id)arg2;
- (void)didStartPullToDismissWithViewingStoryController:(id)arg1;
- (void)replyStoryViewController:(id)arg1 didAppearAtBottomOffset:(double)arg2;
- (void)willHideReplyToStoryViewOnReplyToStoryViewController:(id)arg1;
- (void)willShowReplyToStoryViewOnReplyToStoryViewController:(id)arg1;
- (void)didTapReplyToStoryViewController:(id)arg1;
- (void)pageDidFullyAppearForIndex:(unsigned long long)arg1 onMediaContextViewController:(id)arg2;
- (void)didScrollToOffset:(double)arg1 onMediaContextViewController:(id)arg2;
- (void)hideMyStoryAndGoToFeed:(id)arg1;
- (void)hideMyStoryAndGoToChat:(id)arg1 friend:(id)arg2;
- (void)didTapMediaContextViewController:(id)arg1;
- (void)didHideMediaContextViewController:(id)arg1;
- (void)didShowMediaContextViewController:(id)arg1;
- (void)deleteButtonPressedOnMediaContextViewController:(id)arg1;
- (void)saveButtonPressedOnMediaContextViewController:(id)arg1;
- (void)retryFailedPostButtonPressedOnMediaContextViewController:(id)arg1;
- (_Bool)hasNoVisibleStory;
- (_Bool)isLowerLevel;
- (void)reportSnapController:(id)arg1 didReportSnapWithId:(id)arg2 reportReason:(unsigned long long)arg3;
- (void)reportSnapController:(id)arg1 didDismissReportSnapDialogForSnapWithId:(id)arg2;
- (void)reportSnapController:(id)arg1 didShowReportSnapDialogForSnapWithId:(id)arg2;
- (void)showReportView;
- (void)didLongPress:(id)arg1;
- (void)setupLongPressGestureRecognizer;
- (void)removePlayWhenLoadedObserver;
- (void)batchStateDidChange:(id)arg1;
- (void)unviewedBatchStateDidChange:(id)arg1;
- (void)playWhenLoaded;
- (void)storySnapDidChange:(id)arg1 object:(id)arg2;
- (void)removeStorySnapObserver;
- (void)playWhenStorySnapLoaded:(id)arg1;
- (void)friendStoriesDidBecomeUnloadedWhileViewingStorySnap:(id)arg1;
- (void)didFetchNextLevelFriendStories:(id)arg1 currentStoryId:(id)arg2 isNewlyFetched:(_Bool)arg3;
- (void)cancelSubmittedRequests;
- (void)didTapAffordanceView;
- (void)resetNextLevel;
- (void)navigatingAwayUserInitiated;
- (id)nextLevelController;
- (void)viewDidScroll;
- (void)viewWasSkipped;
- (void)viewDidAppearAtOffset:(double)arg1;
- (void)returningToPreviousView;
- (void)advancingToNextViewWithOffset:(double)arg1;
- (id)getPageViewName;
- (void)viewDidFullyDisappear;
- (void)viewDidPartiallyAppear;
- (void)viewDidFullyAppear;
- (void)didShowTooltip:(id)arg1;
- (id)tooltipText;
- (_Bool)shouldShowExploreSimilarSnapsTooltip;
- (void)showTapToSkipTooltip;
- (void)showSwipeDownToDismissTooltipTappingQuickly:(_Bool)arg1;
- (void)fullScreenLoadingViewDidTapToRetry:(id)arg1;
- (void)didFetchExpiredLiveStory;
- (void)showTapToRetry;
- (void)didFetchLiveStoryMetadataWithSuccess:(_Bool)arg1 response:(id)arg2;
- (void)fetchLiveStoryMetadata;
- (void)resolveLiveStoryDeepLink;
- (void)updateSeenSnapsWithStory:(id)arg1;
- (void)unpauseStory;
- (void)pauseStory;
- (void)stopLoopingStory;
- (_Bool)shouldLogStorySession;
- (void)loopStory;
- (void)hideStoryUserInitiated:(_Bool)arg1;
- (void)hideStory;
- (_Bool)shouldDismissStory:(long long)arg1;
- (void)stopStoryWithReason:(long long)arg1;
- (void)hideStoriesAnimated:(_Bool)arg1;
- (void)myStoryPlayerItemDidReachEnd:(id)arg1;
- (id)friendStoriesCollection;
- (void)forcePullToDismissAnimationCompletion;
- (_Bool)isPullToDismissAnimationCompletionInProgress;
- (_Bool)userIsPullingToDismiss;
- (void)storyDidFinish:(id)arg1;
- (id)friendDisplayName;
- (void)timeLeftDidChange:(id)arg1 forStory:(id)arg2;
- (void)addExpirationObserversToStory:(id)arg1 forViewingType:(long long)arg2;
- (void)skipStory:(id)arg1 forViewingType:(long long)arg2;
- (void)addReplyToStoryViewController;
- (void)showMediaContextView;
- (void)didPreloadVideoStory:(id)arg1 success:(_Bool)arg2 error:(id)arg3;
- (void)didShowStorySnapAfterMediaViewWasShown;
- (void)didShowStory:(id)arg1 timeLeft:(double)arg2 initialView:(_Bool)arg3 success:(_Bool)arg4 error:(id)arg5;
- (_Bool)shouldSetLoadingImageForStory:(id)arg1;
- (void)_setLoadingImageForCurrentAndLowerLevelWithStory:(id)arg1;
- (void)preloadSnapsWhileViewing;
- (void)showFriendStoriesWithInitialView:(_Bool)arg1;
- (void)didShowStorySnapWithSuccess:(_Bool)arg1 error:(id)arg2;
- (void)showStorySnap;
- (_Bool)shouldAutoPlayStoryOnLoad;
- (void)playStory;
- (void)initStoryLoggingSession;
- (void)playStorySnap;
- (void)didTap:(id)arg1;
- (void)_tapToSkip;
- (void)swipeToSkipStory:(id)arg1;
- (_Bool)isForFriendStories:(id)arg1 unviewed:(_Bool)arg2;
- (void)_addAutoAdvanceActions;
- (void)removeMediaViewActions;
- (void)addMediaViewActions;
- (void)addMediaView;
- (void)_screenshotTakenForStory:(id)arg1 viewingType:(long long)arg2;
- (void)userDidTakeScreenshot;
- (void)dealloc;
- (void)hideTimerIfIsOnlyOneSnap;
- (void)setCurrentStoriesTotalTime:(double)arg1;
- (void)updateFinalCircleFrame:(struct CGRect)arg1 iconToHideLayer:(id)arg2 iconToDisplay:(id)arg3;
- (void)setPullToDismissView:(id)arg1;
- (void)setBackgroundViewFactory:(id)arg1;
- (void)didStartPullToDismiss;
- (_Bool)shouldTriggerPullToDismissWithSwipeDirection:(unsigned long long)arg1;
- (double)totalTimeLeftForViewingType:(long long)arg1;
- (long long)viewingType;
- (void)viewDidBecomeActive;
- (void)viewWillResignActive;
- (_Bool)isPlayingIndividualStorySnap;
- (_Bool)isPlayingStory;
- (void)setLeveledThumbnailVC:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)didCompletePullToDismiss;
- (void)loadView;
- (unsigned long long)loadingViewStyle;
- (_Bool)fullLoadingScreenEnabled;
- (id)initWithStorySnap:(id)arg1 userSession:(id)arg2 showContextMenu:(_Bool)arg3;
- (id)initWithFriendStories:(id)arg1 userSession:(id)arg2 deepLinkURL:(id)arg3 unviewed:(_Bool)arg4 storyLoader:(id)arg5 supportsPullToDismiss:(_Bool)arg6 leveledThumbnailVC:(id)arg7 levelNumber:(unsigned long long)arg8 seenSnaps:(id)arg9 showInitialLoadingView:(_Bool)arg10 loggingParameters:(id)arg11 reportSnapController:(id)arg12 storyExploreLogger:(id)arg13;
- (id)initWithFriendStories:(id)arg1 userSession:(id)arg2 deepLinkURL:(id)arg3 unviewed:(_Bool)arg4 storyLoader:(id)arg5 supportsPullToDismiss:(_Bool)arg6 leveledThumbnailVC:(id)arg7 levelNumber:(unsigned long long)arg8 seenSnaps:(id)arg9 showInitialLoadingView:(_Bool)arg10 loggingParameters:(id)arg11 storyExploreLogger:(id)arg12;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

